# Generated by Django 4.2.8 on 2025-12-09 09:34

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('companies', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='companyadmin',
            name='casual_leave_days',
            field=models.IntegerField(default=12),
        ),
        migrations.AddField(
            model_name='companyadmin',
            name='company_industry',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
        migrations.AddField(
            model_name='companyadmin',
            name='company_name',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
        migrations.AddField(
            model_name='companyadmin',
            name='company_setup_completed',
            field=models.BooleanField(default=False, help_text='Whether company setup wizard has been completed'),
        ),
        migrations.AddField(
            model_name='companyadmin',
            name='company_website',
            field=models.URLField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='companyadmin',
            name='currency',
            field=models.CharField(default='INR', max_length=10),
        ),
        migrations.AddField(
            model_name='companyadmin',
            name='personal_leave_days',
            field=models.IntegerField(default=2),
        ),
        migrations.AddField(
            model_name='companyadmin',
            name='setup_completed_at',
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='companyadmin',
            name='sick_leave_days',
            field=models.IntegerField(default=6),
        ),
        migrations.AddField(
            model_name='companyadmin',
            name='timezone',
            field=models.CharField(default='IST', max_length=50),
        ),
        migrations.AddField(
            model_name='companyadmin',
            name='total_employees',
            field=models.IntegerField(default=0),
        ),
        migrations.AddField(
            model_name='companyadmin',
            name='working_hours_end',
            field=models.TimeField(default='18:00'),
        ),
        migrations.AddField(
            model_name='companyadmin',
            name='working_hours_start',
            field=models.TimeField(default='09:00'),
        ),
    ]
