# Generated by Django 4.2.8 on 2025-12-09 11:37

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('companies', '0002_companyadmin_casual_leave_days_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='companyadmin',
            name='avatar',
            field=models.ImageField(blank=True, null=True, upload_to='avatars/'),
        ),
    ]
