# Generated by Django 4.2.8 on 2025-12-10 09:30

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion
import uuid


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('companies', '0003_companyadmin_avatar'),
    ]

    operations = [
        migrations.CreateModel(
            name='Department',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('name', models.CharField(help_text='e.g., HR, Frontend, Backend, Surgery, Cardiology, etc.', max_length=100)),
                ('code', models.CharField(blank=True, help_text='Department code (e.g., HR-01)', max_length=20, null=True, unique=True)),
                ('description', models.TextField(blank=True, help_text='Department description', null=True)),
                ('budget', models.DecimalField(blank=True, decimal_places=2, help_text='Department budget', max_digits=15, null=True)),
                ('is_active', models.BooleanField(default=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('deleted_at', models.DateTimeField(blank=True, null=True)),
                ('company', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='departments', to='companies.company')),
                ('head', models.ForeignKey(blank=True, help_text='Department head/manager', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='department_head_of', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'db_table': 'departments',
                'ordering': ['name'],
                'indexes': [models.Index(fields=['company', 'name'], name='departments_company_6e4335_idx'), models.Index(fields=['company_id', 'head_id'], name='departments_company_f6821a_idx'), models.Index(fields=['is_active'], name='departments_is_acti_a777bd_idx')],
                'unique_together': {('company', 'name')},
            },
        ),
    ]
