# Generated by Django 4.2.8 on 2025-12-10 06:52

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('companies', '0003_companyadmin_avatar'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='HR',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('full_name', models.CharField(max_length=255)),
                ('personal_email', models.EmailField(help_text='Real personal email where credentials are sent', max_length=254)),
                ('phone', models.CharField(blank=True, max_length=20, null=True)),
                ('temp_password_set', models.BooleanField(default=True, help_text='Whether HR is using temporary password')),
                ('password_changed_at', models.DateTimeField(blank=True, null=True)),
                ('profile_completed', models.BooleanField(default=False, help_text='Whether HR has completed their profile after password change')),
                ('profile_completed_at', models.DateTimeField(blank=True, null=True)),
                ('is_active', models.BooleanField(default=True)),
                ('is_verified', models.BooleanField(default=False)),
                ('verified_at', models.DateTimeField(blank=True, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('created_by', models.CharField(default='admin', max_length=255)),
                ('company', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='hr_managers', to='companies.company')),
                ('user', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='hr_profile', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'HR Manager',
                'verbose_name_plural': 'HR Managers',
                'db_table': 'hr_managers',
                'unique_together': {('company', 'user')},
            },
        ),
    ]
