# Generated by Django 4.2.8 on 2025-12-10 09:29

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0001_initial'),
    ]

    operations = [
        migrations.DeleteModel(
            name='HR',
        ),
    ]
