# Generated by Django 4.2.8 on 2025-12-11 11:52

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('users', '0002_delete_hr'),
    ]

    operations = [
        migrations.CreateModel(
            name='User',
            fields=[
                ('id', models.UUIDField(editable=False, primary_key=True, serialize=False)),
                ('email', models.EmailField(db_index=True, max_length=254, unique=True)),
                ('name', models.CharField(max_length=255)),
                ('phone', models.CharField(blank=True, max_length=20, null=True)),
                ('role', models.CharField(choices=[('manager', 'Manager'), ('hr', 'HR'), ('team_lead', 'Team Lead'), ('employee', 'Employee')], db_index=True, default='employee', max_length=50)),
                ('password_hash', models.CharField(max_length=255)),
                ('temp_password', models.BooleanField(db_index=True, default=True)),
                ('profile_completed', models.BooleanField(db_index=True, default=False)),
                ('company_id', models.UUIDField(blank=True, null=True)),
                ('department_id', models.UUIDField(blank=True, null=True)),
                ('password_changed_at', models.DateTimeField(blank=True, null=True)),
                ('profile_completed_at', models.DateTimeField(blank=True, null=True)),
                ('is_active', models.BooleanField(default=True)),
                ('status', models.CharField(default='active', max_length=20)),
                ('employee_type', models.CharField(default='permanent', max_length=20)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
            options={
                'db_table': 'users',
                'managed': False,
            },
        ),
    ]
